# Uncomment the next line to define a global platform for your project
  platform :ios, '14.0'

target 'NyTimes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NyTimes
  pod 'Alamofire', '~> 5.2'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'SwiftLint', '~> 0.41.0'

  target 'NyTimesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NyTimesUITests' do
    # Pods for testing
  end

end
